# Generated by Django 2.2.17 on 2020-11-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20201126_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filetype',
        ),
    ]
