# Generated by Django 2.2.17 on 2020-11-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_remove_file_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.CharField(default='Undefined', max_length=10),
        ),
    ]
